// <auto-generated />
using Caju.Driven.Database.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Caju.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250123143836_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Caju.Models.Balance", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Category", "UserId");

                    b.ToTable("Balances");

                    b.HasData(
                        new
                        {
                            Category = "FOOD",
                            UserId = "123",
                            TotalAmount = 480.00m
                        },
                        new
                        {
                            Category = "MEAL",
                            UserId = "123",
                            TotalAmount = 160.00m
                        },
                        new
                        {
                            Category = "CASH",
                            UserId = "123",
                            TotalAmount = 100.00m
                        },
                        new
                        {
                            Category = "FOOD",
                            UserId = "456",
                            TotalAmount = 300.00m
                        },
                        new
                        {
                            Category = "MEAL",
                            UserId = "456",
                            TotalAmount = 150.00m
                        },
                        new
                        {
                            Category = "CASH",
                            UserId = "456",
                            TotalAmount = 450.00m
                        });
                });

            modelBuilder.Entity("Caju.Models.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mcc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mcc = "5811",
                            Name = "UBER EATS SAO PAULO BR"
                        },
                        new
                        {
                            Id = 2,
                            Mcc = "4444",
                            Name = "UBER TRIP SAO PAULO BR"
                        },
                        new
                        {
                            Id = 3,
                            Mcc = "5555",
                            Name = "PICPAY*BILHETUNICO GOIANIA BR"
                        },
                        new
                        {
                            Id = 4,
                            Mcc = "5811",
                            Name = "PAG*JoseDaSilva RIO DE JANEIRO BR"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
